### ISSUE TITLE
Can we get rid of "type", but then how to define an integer?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/whip#14]
The syntax still lists `type` at https://github.com/inbo/whip/blame/master/docs/syntax.md#L398, but that is not defined. I hope that specification can be removed, but than the question remains how that example can be redefined:

```
postalcode:
  type: integer
```

@stijnvanhoey, maybe as:

```
postalcode:
  numberformat: x # How can you define an integer of unspecified length?
```

**Comment by peterdesmet** [comment]
Same for defining an unspecified float, would that be:

```
decimalLatitude:
  numberformat: '.'
```

**Comment by stijnvanhoey** [comment]
"I hope that specification can be removed" 

Why getting rid of the `type` specification? Do we want  (and can we) capture all the use-cases of having integer or floats using the `numberformat` specification, taking into account we add the your two suggestions:

```
postalcode:
  numberformat: x # How can you define an integer of unspecified length?
decimalLatitude:
  numberformat: '.'
```
