### ISSUE TITLE
Handling integers inside schema definition

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/whip#22]
Consider the following example:

```
coordinateUncertaintyInMeters:
  empty: true
  if:
    - verbatimCoordinateSystem:
        allowed: UTM 1km
      numberformat: x
      allowed: 707
    - verbatimCoordinateSystem:
        allowed: UTM 5km
      numberformat: x
      allowed: 3536
```

Where the `allowed` values are somteimes integers (parsing this with default yaml-libraries). The question is how to handle this:

- Always expect (when loading the yaml-schema) that `allowed` need to be strings and pre-format it as such after loading
- Expect from the user to be explicit about the string, by requiring quotes: `allowed: '3536'`
- Provide a 'SchemaError' (or 'SpecificationError'), stating that allowed need to be string/list as for integers, the combination `min`/`max` is provided. However what with `allowed: ['4', '27']`?
